global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ '172.17.0.1:9095' ]
  - job_name: flower
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ '172.17.0.1:5555' ]
  - job_name: monitoring
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'host.docker.internal', 'host.docker.internal:8000', '172.17.0.1:8000' ]