global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: flower
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'flower:5555' ]
    basic_auth:
      username: 'debug'
      password: 'debug'
  - job_name: monitoring
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'nginx', 'django:8000' ]