global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ '0.0.0.0:9095' ]
  - job_name: flower
    static_configs:
      - targets: [ '0.0.0.0:5555' ]